# Use postgres/example user/password credentials
version: '3.1'

networks:
  mynetwork:

services:
  # https://trino.io
  dw-trino:
    image: trinodb/trino:latest
    container_name: dw-trino
    restart: always
    depends_on:
      - dw-postgres
    ports:
      - "9900:8080"
    volumes:
      - ./configs/trino/catalogs/postgresql.properties:/etc/trino/catalog/postgresql.properties
    networks:
      - mynetwork

  dw-postgres:
    image: postgres:14.3
    container_name: dw-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "${POSTGRES_USER_ID}"
      POSTGRES_PASSWORD: "${POSTGRES_USER_PW}"
    networks:
      - mynetwork
